name: Create Issue

on:
  workflow_dispatch:
  schedule:
    - cron: 0,5,10,15,20,25,30,35,40,45,50,55 * * * *

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Issue for weekly todo
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "sujin-park"
          labels: "Feature"
          title: "Weekly Todo"
          body: |
            ### Agenda

            - [ ] project setup
            - [ ] xxx

          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}